### ISSUE TITLE
Feature Request: Image selection for a single query

### ISSUE THREAD

**Issue by s-ankur** [piyush27ranjan/Add-cover-art#51]
We already have the ability to download multiple images for a single query. Currently we just take the first image that we find. We should add buttons to select which of the downloaded images we want to apply

**Comment by s-ankur** [comment]
[Image For reference](https://addcoverart.slack.com/files/UEMBDHT33/FENC6GRNZ/whatsapp_image_2018-12-07_at_7.05.28_pm.jpeg)

**Comment by piyush27ranjan** [comment]
Its a great idea but it already takes enough time to download a single image

**Comment by s-ankur** [comment]
I agree. We can use iterators to download stuff on demand

**Comment by piyush27ranjan** [comment]
Good work
