### ISSUE TITLE
Optimization: Dont save downloaded images to disk

### ISSUE THREAD

**Issue by s-ankur** [piyush27ranjan/Add-cover-art#52]
Instead download and return the image data directly instead of saving to disk. This will reduce some overhead of saving then loading the images.

**Comment by piyush27ranjan** [comment]
It might save us time but i cant think of a way to achieve this. Eyed3 needs an actual image.

**Comment by s-ankur** [comment]
Eyed3 requires a file for the mp3 not the jpg
  audiofile.tag.images.set(3, open(art_filename, 'rb').read(), 'image/jpeg')
                                                ^
Substitute data here
Here we can use the 
response= urllib.request.urlopen(image_url)
data= response.read()

**Comment by s-ankur** [comment]
> We can start downloading the image the moment we find the link
unless we use re instead of bs4 there is no way to do this afiak atm
but i improved it slightly with #54
